com.example.trainawearapplication.UdpClientHandlerPlank Class Reference
Public Member Functions
UdpClientHandlerPlank ()
void handleMessage (Message msg)
Method used by ClientListenPlank thread handler to display the messages (IP address and feedback) in Plank activity.
Static Public Attributes
static final int UPDATE_STATE = 0
static final int UPDATE_MSG = 1
static final int UPDATE_END = 2
Package Attributes
final String TAG = `UdpClientHandlerPlank`
UdpClientHandlerPlank udpClientHandler
Private Member Functions
void updateRxMsgPlank (String rxmsg)
Method that updates the receive field with the received String; used to read the String.
void updateStatePlank (String state)
Method that displays the IP address in invisible field.
Private Attributes
MainActivity parent
Detailed Description
Definition at line 19 of file UdpClientHandlerPlank.java.
Constructor & Destructor Documentation
UdpClientHandlerPlank()
com.example.trainawearapplication.UdpClientHandlerPlank.UdpClientHandlerPlank () [inline]
Definition at line 33 of file UdpClientHandlerPlank.java.
                                   {
        super();
        this.parent = parent;
    }
References com.example.trainawearapplication.UdpClientHandlerPlank.parent.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage().
Member Function Documentation
handleMessage()
void com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage (Message msg) [inline]
Method used by ClientListenPlank thread handler to display the messages (IP address and feedback) in Plank activity.
Parameters
msg UDP data packet displayed using UpdateFeedback interface
Definition at line 45 of file UdpClientHandlerPlank.java.
                                           {
        udpClientHandler = new UdpClientHandlerPlank();
        switch (msg.what){
            case UPDATE_STATE:
                udpClientHandler.updateStatePlank((String)msg.obj);
                break;
            case UPDATE_MSG:
                udpClientHandler.updateRxMsgPlank((String)msg.obj);
                textFeedbackPlank.setText(showFeedback((String)msg.obj));
                break;
            default:
                super.handleMessage(msg);
        }
    }
References com.example.trainawearapplication.UdpClientHandlerPlank.udpClientHandler, com.example.trainawearapplication.UdpClientHandlerPlank.UdpClientHandlerPlank(), com.example.trainawearapplication.UdpClientHandlerPlank.UPDATE_MSG, com.example.trainawearapplication.UdpClientHandlerPlank.UPDATE_STATE, com.example.trainawearapplication.UdpClientHandlerPlank.updateRxMsgPlank(), and com.example.trainawearapplication.UdpClientHandlerPlank.updateStatePlank().
updateRxMsgPlank()
void com.example.trainawearapplication.UdpClientHandlerPlank.updateRxMsgPlank (String rxmsg) [inline], [private]
Method that updates the receive field with the received String; used to read the String.
Parameters
rxmsg
Definition at line 64 of file UdpClientHandlerPlank.java.
                                                {
        textViewRxPlank.setText(rxmsg + "\n");
        Log.d(TAG, "on text update");
    }
References com.example.trainawearapplication.UdpClientHandlerPlank.TAG.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage().
updateStatePlank()
void com.example.trainawearapplication.UdpClientHandlerPlank.updateStatePlank (String state) [inline], [private]
Method that displays the IP address in invisible field.
Parameters
state Variable displays the IP address when the handskahe occurs
Definition at line 75 of file UdpClientHandlerPlank.java.
                                                {
        Log.d(TAG,"update state");
        textViewStatePlank.setText(state);
    }
References com.example.trainawearapplication.UdpClientHandlerPlank.TAG.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage().
Member Data Documentation
parent
MainActivity com.example.trainawearapplication.UdpClientHandlerPlank.parent [private]
Definition at line 28 of file UdpClientHandlerPlank.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.UdpClientHandlerPlank().
TAG
final String com.example.trainawearapplication.UdpClientHandlerPlank.TAG = `UdpClientHandlerPlank` [package]
Definition at line 21 of file UdpClientHandlerPlank.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.updateRxMsgPlank(), and com.example.trainawearapplication.UdpClientHandlerPlank.updateStatePlank().
udpClientHandler
UdpClientHandlerPlank com.example.trainawearapplication.UdpClientHandlerPlank.udpClientHandler [package]
Definition at line 23 of file UdpClientHandlerPlank.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage().
UPDATE_END
final int com.example.trainawearapplication.UdpClientHandlerPlank.UPDATE_END = 2 [static]
Definition at line 27 of file UdpClientHandlerPlank.java.
UPDATE_MSG
final int com.example.trainawearapplication.UdpClientHandlerPlank.UPDATE_MSG = 1 [static]
Definition at line 26 of file UdpClientHandlerPlank.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage(), com.example.trainawearapplication.ClientListenPlank.run(), and com.example.trainawearapplication.ClientListen.run().
UPDATE_STATE
final int com.example.trainawearapplication.UdpClientHandlerPlank.UPDATE_STATE = 0 [static]
Definition at line 25 of file UdpClientHandlerPlank.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerPlank.handleMessage(), com.example.trainawearapplication.ClientListenPlank.run(), com.example.trainawearapplication.ClientListen.run(), and com.example.trainawearapplication.ClientListenPlank.sendState().
The documentation for this class was generated from the following file:
D:/Firstapp/TrainAwearapplication/app/src/main/java/com/example/trainawearapplication/UdpClientHandlerPlank.java