com.example.trainawearapplication.ClassicSquatSwitchTest Class Reference
@biref Testing the Switch method in ClassicSquat
Public Member Functions
void testSwitchCase0 ()
Test method for ClassicSquat.
void testSwitchCase1 ()
void testSwitchCase2 ()
void testSwitchCase3 ()
void testSwitchCase6 ()
void testSwitchCaseDefault ()
void testSwitchCaseFail ()
Static Private Attributes
static ClassicSquat mActivitySquat
static final int TEST_CASE1 = 0
static final int TEST_CASE2 = 2
static TextView outputText
Detailed Description
@biref Testing the Switch method in ClassicSquat
Definition at line 22 of file ClassicSquatSwitchTest.java.
Member Function Documentation
testSwitchCase0()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase0 () [inline]
Test method for ClassicSquat.
Definition at line 38 of file ClassicSquatSwitchTest.java.
                                 {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "0";
        assertEquals("Ready to start", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCase1()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase1 () [inline]
Definition at line 49 of file ClassicSquatSwitchTest.java.
                                 {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "1";
        assertEquals("Let's go!", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCase2()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase2 () [inline]
Definition at line 60 of file ClassicSquatSwitchTest.java.
                                 {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "2";
        assertEquals("Knees caving in: Keep your knees in line with your toes", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCase3()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase3 () [inline]
Definition at line 72 of file ClassicSquatSwitchTest.java.
                                 {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "3";
        assertEquals("Your back is bending, keep it straight while tensing your abs", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCase6()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase6 () [inline]
Definition at line 83 of file ClassicSquatSwitchTest.java.
                                 {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "6";
        assertEquals("If you keep your hips steady, the abs are working harder", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCaseDefault()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseDefault () [inline]
Definition at line 94 of file ClassicSquatSwitchTest.java.
                                       {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "anything else";
        assertEquals("You're doing great, keep going!", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
testSwitchCaseFail()
void com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseFail () [inline]
Definition at line 105 of file ClassicSquatSwitchTest.java.
                                    {
        mActivitySquat = new ClassicSquat();
        String instructionDef = "2";
        assertEquals("You're doing great, keep going!", mActivitySquat.showFeedback(instructionDef));
    }
References com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat, and com.example.trainawearapplication.ClassicSquat.showFeedback().
Member Data Documentation
mActivitySquat
ClassicSquat com.example.trainawearapplication.ClassicSquatSwitchTest.mActivitySquat [static], [private]
Definition at line 24 of file ClassicSquatSwitchTest.java.
Referenced by com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase0(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase1(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase2(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase3(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCase6(), com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseDefault(), and com.example.trainawearapplication.ClassicSquatSwitchTest.testSwitchCaseFail().
outputText
TextView com.example.trainawearapplication.ClassicSquatSwitchTest.outputText [static], [private]
Definition at line 28 of file ClassicSquatSwitchTest.java.
TEST_CASE1
final int com.example.trainawearapplication.ClassicSquatSwitchTest.TEST_CASE1 = 0 [static], [private]
Definition at line 26 of file ClassicSquatSwitchTest.java.
TEST_CASE2
final int com.example.trainawearapplication.ClassicSquatSwitchTest.TEST_CASE2 = 2 [static], [private]
Definition at line 27 of file ClassicSquatSwitchTest.java.
The documentation for this class was generated from the following file:
D:/Firstapp/TrainAwearapplication/app/src/test/java/com/example/trainawearapplication/ClassicSquatSwitchTest.java