com.example.trainawearapplication.UdpClientHandlerBicep Class Reference
Public Member Functions
UdpClientHandlerBicep ()
void handleMessage (Message msg)
Static Public Attributes
static final int UPDATE_STATE = 0
static final int UPDATE_MSG = 1
static final int UPDATE_END = 2
Private Member Functions
void updateRxMsg (String rxmsg)
Method that updates the receive field with the received String; used to read the String.
void updateState (String state)
Method that displays the IP address in invisible field.
Private Attributes
MainActivity parent
Detailed Description
Definition at line 19 of file UdpClientHandlerBicep.java.
Constructor & Destructor Documentation
UdpClientHandlerBicep()
com.example.trainawearapplication.UdpClientHandlerBicep.UdpClientHandlerBicep ()
Definition at line 33 of file UdpClientHandlerBicep.java.
                                   {
        super();
        this.parent = parent;
    }
References com.example.trainawearapplication.UdpClientHandlerBicep.parent.
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage().
Member Function Documentation
handleMessage()
void com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage (Message msg)
Definition at line 40 of file UdpClientHandlerBicep.java.
                                           {
        udpClientHandler = new UdpClientHandlerBicep();
        switch (msg.what){
            case UPDATE_STATE:
                udpClientHandler.updateState((String)msg.obj);
                break;
            case UPDATE_MSG:
                udpClientHandler.updateRxMsg((String)msg.obj);
                textFeedback.setText(showFeedback((String)msg.obj));
                break;
            default:
                super.handleMessage(msg);
        }
    }
References com.example.trainawearapplication.UdpClientHandlerBicep.UdpClientHandlerBicep(), com.example.trainawearapplication.UdpClientHandlerBicep.UPDATE_MSG, com.example.trainawearapplication.UdpClientHandlerBicep.UPDATE_STATE, com.example.trainawearapplication.UdpClientHandlerBicep.updateRxMsg(), and com.example.trainawearapplication.UdpClientHandlerBicep.updateState().
updateRxMsg()
void com.example.trainawearapplication.UdpClientHandlerBicep.updateRxMsg (String rxmsg) [private]
Method that updates the receive field with the received String; used to read the String.
Parameters
rxmsg
Definition at line 59 of file UdpClientHandlerBicep.java.
                                           {
        textViewRx.setText(rxmsg + "\n");
        Log.d(TAG, "on text update");
    }
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage().
updateState()
void com.example.trainawearapplication.UdpClientHandlerBicep.updateState (String state) [private]
Method that displays the IP address in invisible field.
Parameters
state Variable displays the IP address when the handskahe occurs
Definition at line 70 of file UdpClientHandlerBicep.java.
                                           {
        Log.d(TAG,"update state");
        textViewState.setText(state);
    }
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage().
Member Data Documentation
parent
MainActivity com.example.trainawearapplication.UdpClientHandlerBicep.parent [private]
Definition at line 28 of file UdpClientHandlerBicep.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.UdpClientHandlerBicep().
UPDATE_END
final int com.example.trainawearapplication.UdpClientHandlerBicep.UPDATE_END = 2 [static]
Definition at line 27 of file UdpClientHandlerBicep.java.
UPDATE_MSG
final int com.example.trainawearapplication.UdpClientHandlerBicep.UPDATE_MSG = 1 [static]
Definition at line 26 of file UdpClientHandlerBicep.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage(), and com.example.trainawearapplication.ClientListenBicep.run().
UPDATE_STATE
final int com.example.trainawearapplication.UdpClientHandlerBicep.UPDATE_STATE = 0 [static]
Definition at line 25 of file UdpClientHandlerBicep.java.
Referenced by com.example.trainawearapplication.UdpClientHandlerBicep.handleMessage(), com.example.trainawearapplication.ClientListenBicep.run(), and com.example.trainawearapplication.ClientListenBicep.sendState().
The documentation for this class was generated from the following file:
D:/cloned repo trainawear/train-A-wear/Phone App/app/src/main/java/com/example/trainawearapplication/UdpClientHandlerBicep.java